namespace RSolution
{
    [default_interface]
    runtimeclass AlarmPage : Microsoft.UI.Xaml.Controls.Page
    {
        AlarmPage();
        Int32 MyProperty;
        Windows.Foundation.Collections.IObservableVector<Object> LogEntries{ get; };
    }
}
